build:
  system_packages:
    - "wget"
    - "ffmpeg"
    - "libgl1-mesa-glx"
  python_packages:
    - "websocket-client==1.6.4"
    - "accelerate==0.23.0"
    - "opencv-python==4.10.0.84"
    - "boto3==1.35.9"
    - "pillow==10.4.0"
    - "torchvision==0.19.0"
    - "einops==0.8.0"
    - "transformers==4.44.2"
    - "scipy==1.14.1"
    - "torchsde==0.2.6"
    - "aiohttp==3.10.5"
    - "safetensors==0.4.4"
    - "pydantic==2.8.2"
    - "groq==0.10.0"
    - "aiohttp-sse==2.2.0"
    - "spandrel==0.3.4"
    - "kornia==0.7.3"
    - "torchaudio==2.4.0"
    - "matplotlib==3.8.0"
    - "scikit-image==0.24.0"
    - "simpleeval==0.9.13"
    - "imageio-ffmpeg==0.5.1"
    - "pypng==0.20220715.0"
